# Generated by Django 5.2 on 2025-04-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='game_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
