# Generated by Django 5.2 on 2025-04-12 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_games_game_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Games',
            new_name='Game',
        ),
        migrations.RenameModel(
            old_name='Genres',
            new_name='Genre',
        ),
    ]
