# Generated by Django 5.2 on 2025-04-22 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_rename_games_game_rename_genres_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_image',
            field=models.ImageField(null=True, upload_to='games/'),
        ),
        migrations.CreateModel(
            name='Consoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('console_name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('price', models.FloatField()),
                ('console_image', models.ImageField(null=True, upload_to='consoles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='console_company_name', to='catalog.company')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='console_genre', to='catalog.genre')),
            ],
        ),
    ]
