# Generated by Django 5.2 on 2025-04-22 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_game_game_image_consoles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consoles',
            name='genre',
        ),
    ]
